version: '3.7'

networks:
  hestia-network:
    name: hestia-network

volumes:
  hestia-database-volume:
    name: hestia-database-volume

services:
  hestia-bot:
    container_name: hestia-bot
    healthcheck:
      test: cat /proc/1/cmdline || exit 1
      start_period: 5s
    image: wtfloris/hestia-bot:latest
    networks: 
      - hestia-network
    restart: unless-stopped
    volumes:
      - /root/hestia/data:/data
    working_dir: /hestia
    environment:
      - OWN_CHAT_ID=AAA
      - TOKEN=AAA
      - DB_HOST=hestia-database-dev
      - DB_PORT=5432
      - DB_DB=hestia
      - DB_USER=postgres
      - DB_PASSWORD=AAA

  hestia-scraper:
    container_name: hestia-scraper
    healthcheck:
      test: pgrep cron || exit 1
      start_period: 5s
    image: wtfloris/hestia-scraper:latest
    networks: 
      - hestia-network
    restart: unless-stopped
    volumes:
      - /root/hestia/data:/data
    working_dir: /scraper
    environment:
      - OWN_CHAT_ID=AAA
      - TOKEN=AAA
      - DB_HOST=hestia-database-dev
      - DB_PORT=5432
      - DB_DB=hestia
      - DB_USER=postgres
      - DB_PASSWORD=AAA

  hestia-database:
    container_name: hestia-database
    image: postgres:latest
    networks: 
      - hestia-network
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped 
    volumes:
      - hestia-database-volume:/var/lib/postgresql/data
